
INSERT INTO SYSTEMUSER(USERNAME,PASSWORD) VALUES ('Jan','abcde')
INSERT INTO SYSTEMUSER(USERNAME,PASSWORD) VALUES ('Ole','secret')
INSERT INTO SYSTEMUSER(USERNAME,PASSWORD) VALUES ('Ida','test')
INSERT INTO SYSTEMUSER(USERNAME,PASSWORD) VALUES ('Janne','test')
INSERT INTO SYSTEMUSER(USERNAME,PASSWORD) VALUES ('Ian','test')
INSERT INTO SYSTEMUSER(USERNAME,PASSWORD) VALUES ('Per','test')
INSERT INTO SYSTEMUSER(USERNAME,PASSWORD) VALUES ('Peter','test')
INSERT INTO SYSTEMUSER(USERNAME,PASSWORD) VALUES ('Donald Duck','test')